ATTENTION: This operation should not be executed in a production environment.

CREATE TABLE user (user_id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) DEFAULT NULL, email VARCHAR(100) NOT NULL, display_name VARCHAR(50) DEFAULT NULL, password VARCHAR(128) NOT NULL, last_login DATETIME DEFAULT NULL, last_ip INT DEFAULT NULL, register_time DATETIME NOT NULL, register_ip INT NOT NULL, active TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(user_id)) ENGINE = InnoDB;
CREATE TABLE user_meta (meta_key VARCHAR(255) NOT NULL, user_id INT NOT NULL, meta LONGTEXT NOT NULL, INDEX IDX_AD7358FCA76ED395 (user_id), PRIMARY KEY(meta_key, user_id)) ENGINE = InnoDB;
ALTER TABLE user_meta ADD CONSTRAINT FK_AD7358FCA76ED395 FOREIGN KEY (user_id) REFERENCES user (user_id);
